const regexHeaderComment = `WARNING: Do not edit this file!!!

The file "src/regex_editable.js" contains the source for this regex.
Run "npm run build:regex to generate this file again after editing the source."
`

export default {
  plugins: [
    [
      "babel-plugin-transform-regex",
      {
        removeImport: true,
        headerCommend: regexHeaderComment,
        disableUnicodeSets: true,
        optimize: true,
      }
    ]
  ]
  
}
